// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApiCrudOperation.Models;

namespace ProductsApiCrudOperation.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20210220025526_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsApiCrudOperation.Models.Product", b =>
                {
                    b.Property<int>("prodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("YearOfManuf")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("prodManufacturer")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("prodPrice")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<int>("prodRating")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("prodType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("prodId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
